image: node:18  # Use appropriate image for your stack

pipelines:
  branches:
    develop:
      - step:
          name: Deploy to Staging
          script:
            - echo "Deploying to Staging..."
            - mkdir -p ~/.ssh
            - echo "$SSH_KEY" > ~/.ssh/id_rsa
            - chmod 600 ~/.ssh/id_rsa
            - echo "DB_HOST=$DB_HOST" > .env
            - echo "DB_USER=$DB_USER" >> .env
            - echo "DB_PASSWORD=$DB_PASSWORD" >> .env
            - echo "DB_PORT=$DB_PORT" >> .env
            - scp -o StrictHostKeyChecking=no .env $SSH_USER@$UAT_HOST:$UAT_PATH/.env
            - echo 'export NVM_DIR="$HOME/.nvm"' >> ~/.bashrc
            - echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> ~/.bashrc
            - source ~/.bashrc
            - ssh -o StrictHostKeyChecking=no $SSH_USER@$UAT_HOST "cd $UAT_PATH && git pull origin develop && npm install && node app.js"
  
  
  # && npm install && pm2 restart all

    main:
      - step:
          name: Deploy to Production
          script:
            - echo "Deploying to Production..."
            - mkdir -p ~/.ssh
            - echo "$SSH_KEY" > ~/.ssh/id_rsa
            - chmod 600 ~/.ssh/id_rsa
            - ssh -o StrictHostKeyChecking=no $SSH_USER@$PROD_HOST "cd $PROD_PATH && git pull origin main && npm install && pm2 restart all"