image: node:18  # Use appropriate image for your stack

pipelines:
  branches:
    develop:
      - step:
          name: Deploy to Staging
          script:
            - echo "Deploying to Staging..."
            - echo "อาลำ สุดหล่อ สุดเท่"
            - mkdir -p ~/.ssh
            - echo "$SSH_KEY" > ~/.ssh/id_rsa
            - chmod 600 ~/.ssh/id_rsa
            - ssh -o StrictHostKeyChecking=no $SSH_USER@$UAT_HOST "cd $UAT_PATH && git pull origin develop"
  
  
  # && npm install && pm2 restart all

    main:
      - step:
          name: Deploy to Production
          script:
            - echo "Deploying to Production..."
            - mkdir -p ~/.ssh
            - echo "$SSH_KEY" > ~/.ssh/id_rsa
            - chmod 600 ~/.ssh/id_rsa
            - ssh -o StrictHostKeyChecking=no $SSH_USER@$PROD_HOST "cd $PROD_PATH && git pull origin main && npm install && pm2 restart all"